# Generated by Django 5.2.17 on 2026-08-21 07:02

import django.core.validators
import portfolio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=150)),
                ('field_of_study', models.CharField(max_length=150)),
                ('start_year', models.PositiveSmallIntegerField()),
                ('end_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-start_year'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150)),
                ('headline', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=150)),
                ('avatar', models.ImageField(upload_to='profile/avatar/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Only JPG, JPEG, PNG, and WEBP images are allowed.'), portfolio.validators.validate_image_size])),
                ('resume', models.FileField(upload_to='profile/resume/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='The resume must be a PDF file.'), portfolio.validators.validate_resume_size])),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('x_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('is_available_for_hire', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Owner profile',
                'verbose_name_plural': 'Owner profile',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full-time'), ('PART_TIME', 'Part-time'), ('INTERNSHIP', 'Internship'), ('FREELANCE', 'Freelance'), ('CONTRACT', 'Contract')], max_length=20)),
                ('location', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('company_url', models.URLField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-start_date', 'display_order'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('end_date__isnull', True), ('is_current', True)), models.Q(('end_date__isnull', False), ('is_current', False)), _connector='OR'), name='experience_current_end_date_valid'), models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gt', models.F('start_date')), _connector='OR'), name='experience_end_after_start')],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('FRONTEND', 'Frontend'), ('BACKEND', 'Backend'), ('DATABASE', 'Database'), ('DEVOPS', 'DevOps'), ('TOOLS', 'Tools'), ('SOFT_SKILL', 'Soft skill')], max_length=20)),
                ('proficiency', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Proficiency must be at least 1.'), django.core.validators.MaxValueValidator(100, message='Proficiency must not exceed 100.')])),
                ('icon', models.CharField(blank=True, help_text='Optional icon name, for example: python.', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('proficiency__gte', 1), ('proficiency__lte', 100)), name='skill_proficiency_between_1_and_100')],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('summary', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(upload_to='projects/covers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Only JPG, JPEG, PNG, and WEBP images are allowed.'), portfolio.validators.validate_image_size])),
                ('category', models.CharField(choices=[('WEB', 'Web'), ('MOBILE', 'Mobile'), ('API', 'API'), ('ML', 'Machine learning'), ('OTHER', 'Other')], max_length=20)),
                ('live_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('completed_date', models.DateField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('tech_stack', models.ManyToManyField(related_name='projects', to='portfolio.skill')),
            ],
            options={
                'ordering': ['display_order', '-completed_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('live_url', ''), _negated=True), models.Q(('github_url', ''), _negated=True), _connector='OR'), name='project_requires_live_or_github_url')],
            },
        ),
    ]
